
spring:

  application:

    name: produit-service

  datasource:

    url: jdbc:mysql://mysql:3306/produit_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

    username: root

    password:

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:

    database-platform: org.hibernate.dialect.MySQLDialect

    hibernate:

      ddl-auto: update

    show-sql: true

  data:

    redis:

      host: redis

      port: 6379

    repositories:

      enabled: false

  cache:

    type: redis

  main:

    allow-circular-references: true

server:

  port: 8082

app:

  jwt:

    secret: produit-service-groupeisi-secret-key-tres-longue-et-securisee-2024

    expiration: 86400000

springdoc:

  api-docs:

    path: /api-docs

  swagger-ui:

    path: /swagger-ui.html

